### ISSUE TITLE
Errors encountered in keyboardmap; not compiled

### ISSUE THREAD

**Issue by uurcan7** [hexvalid/Linux-CapsLock-Delay-Fixer#20]
diyezuurca@diyezuurca-HP-Laptop-15-db1xxx:~$ bash -ic "sh /home/diyezuurca/İndirilenler/u7cldf/bootstrap.sh"

syntax error: line 1391 of keyboardmap
last scanned symbol is: type
Errors encountered in keyboardmap; not compiled.
/
diyezuurca@diyezuurca-HP-Laptop-15-db1xxx:~$ bash "/home/diyezuurca/İndirilenler/u7cldf/bootstrap.sh"

syntax error: line 1391 of keyboardmap
last scanned symbol is: type
Errors encountered in keyboardmap; not compiled.

**Comment by ahobsonsayers** [comment]
This seems like a duplicate of #19
