### ISSUE TITLE
Disables capslock instead

### ISSUE THREAD

**Issue by JBoughter** [hexvalid/Linux-CapsLock-Delay-Fixer#6]
I tried to use the script, yet upon usage, my caps lock key does nothing until I restart the machine. The LED stops working and the caps lock key stops functioning as well.

**Comment by nitrogenous** [comment]
I have the same issue, Caps-Lock not working

**Comment by hexvalid** [comment]
Did you have `fixpatch` file on current directory?

**Comment by nitrogenous** [comment]
> Did you have `fixpatch` file on current directory?

Yes, I have but I already fix that issue with another script

**Comment by rotemreiss** [comment]
Same problem on fresh Ubuntu 18.04 as well.
Cloned the repo. and have the fixpatch file..
@nitrogenous Can you share the other script please?

**Comment by nitrogenous** [comment]
@rotemreiss Here's the other script but you have to execute that at every startup. 
https://github.com/nitrogenous/Remove-Caps-Lock-Delay

**Comment by nitrogenous** [comment]
> Same problem on fresh Ubuntu 18.04 as well.
> Cloned the repo. and have the fixpatch file..
> @nitrogenous Can you share the other script please?

@rotemreiss Here's the other script but you have to execute that in every startup.
https://github.com/nitrogenous/Remove-Caps-Lock-Delay
