### ISSUE TITLE
This code kills my caps lock key.

### ISSUE THREAD

**Issue by vitorpiovezam** [hexvalid/Linux-CapsLock-Delay-Fixer#9]
On Linux Deepin 15.11 (debian based), run this command kill my caps lock key. Changing keyboard style at configurations bring her back (with the same delay problem).

**Comment by ericmilaneze** [comment]
> On Linux Deepin 15.11 (debian based), run this command kill my caps lock key. Changing keyboard style at configurations bring her back (with the same delay problem).

Hi, did you get any help? I'm having the same issue.

**Comment by WilliamVernaschi** [comment]
When I used the terminal to execute the code my caps also stopped working, but when I used the command provided by OP to execute the code (bash -ic "sh bootstrap.sh"), it worked.

**Comment by AtilioA** [comment]
Make sure `fixpatch` is in the same directory of the other 2 files. If the problem persist you can also try [this other script](https://askubuntu.com/a/574746)

**Comment by Katekko** [comment]
I'm on Ubuntu 20.04, worked like a charm here.

**Comment by ExLog** [comment]
Tested on
- Manjaro XFCE, Worked
- Manjaro GNOME (Wayland) Doesn't work. but work on GNOME On Xorg
- Archlabs GNOME on Xorg worked
- Archlabs Budgie, doesn't work

**Comment by SanoranX** [comment]
Tried on both Debian and Ubuntu, everything is working.
